baseURL = "https://workshop.genesys.com/"
languageCode = "en-us"
title = "Genesys Experience as a Service"
theme = "modernize"
metaDataFormat = "yaml"
relativeURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
  
# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[Languages.sp]
title = "Documentación para el tema Hugo Learn"
weight = 2
languageName = "Español"
